spring:
  application:
    name: "Service Payment"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${application.keycloak.url}/realms/microservices
          jwk-set-uri: ${application.keycloak.url}/realms/microservices/protocol/openid-connect/certs

application:
  keycloak:
    url: http://localhost:9595/auth

management:
  server:
    port: 9292
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full
  metrics:
    distribution:
      percentiles:
        spring.rabbitmq.listener: 0.95
        http.server.requests: 0.95

springdoc:
  api-docs:
    path: /skills/v1/api-docs
  swagger-ui:
    path: /skills/v1/api-docs/swagger-ui.html
    oauth:
      client-id: swagger-ui-admin-implicit