spring:
  application:
    name: "OAuth2 for dummy"

springdoc:
  api-docs:
    path: /skills/v1/api-docs
  swagger-ui:
    path: /skills/v1/api-docs/swagger-ui.html
logging:
  level:
    org.springframework.security: TRACE
